"""Static language lists per transcription provider.

Source URLs (verify against these before any edit):
  - OpenAI Whisper: https://github.com/openai/whisper/blob/main/whisper/tokenizer.py
  - Deepgram:       https://developers.deepgram.com/docs/models-languages-overview
  - ElevenLabs:     https://elevenlabs.io/speech-to-text  (Scribe v1)
  - Sarvam:         https://docs.sarvam.ai/api-reference-docs/speech-to-text/transcribe
  - Local:          faster-whisper, same set as OpenAI Whisper.

Maintenance rules (see CLAUDE.md → "Updating provider language lists"):
  1. Each entry's `code` MUST be the EXACT code the provider's API accepts —
     no translation. We use whatever format the upstream expects.
  2. "auto" is pinned by the client; do not include it here.
  3. For Deepgram, entries with `"model": "nova"` route to the legacy Nova
     model. The selector in deepgram.py:47 reads this. Currently only
     `hi-Latn` needs it.
  4. OpenRouter has no canonical list — it takes a prose instruction in the
     prompt. PROVIDER_LANGUAGES["openrouter"] is None.
  5. After editing, write a short journal entry under docs/building/journal/
     noting what changed and why (keeps the audit trail honest).

Last refreshed from upstream: 2026-04-18
"""

from __future__ import annotations

# ── OpenAI Whisper / Local ───────────────────────────────────────────────────
# Same set for both. Codes are ISO 639-1 (Whisper's canonical IDs).
WHISPER_LANGUAGES: list[dict[str, str]] = [
    {"code": "af", "name": "Afrikaans"},
    {"code": "sq", "name": "Albanian"},
    {"code": "am", "name": "Amharic"},
    {"code": "ar", "name": "Arabic"},
    {"code": "hy", "name": "Armenian"},
    {"code": "as", "name": "Assamese"},
    {"code": "az", "name": "Azerbaijani"},
    {"code": "ba", "name": "Bashkir"},
    {"code": "eu", "name": "Basque"},
    {"code": "be", "name": "Belarusian"},
    {"code": "bn", "name": "Bengali"},
    {"code": "bs", "name": "Bosnian"},
    {"code": "br", "name": "Breton"},
    {"code": "bg", "name": "Bulgarian"},
    {"code": "my", "name": "Burmese"},
    {"code": "yue", "name": "Cantonese"},
    {"code": "ca", "name": "Catalan"},
    {"code": "zh", "name": "Chinese"},
    {"code": "hr", "name": "Croatian"},
    {"code": "cs", "name": "Czech"},
    {"code": "da", "name": "Danish"},
    {"code": "nl", "name": "Dutch"},
    {"code": "en", "name": "English"},
    {"code": "et", "name": "Estonian"},
    {"code": "fo", "name": "Faroese"},
    {"code": "fi", "name": "Finnish"},
    {"code": "fr", "name": "French"},
    {"code": "gl", "name": "Galician"},
    {"code": "ka", "name": "Georgian"},
    {"code": "de", "name": "German"},
    {"code": "el", "name": "Greek"},
    {"code": "gu", "name": "Gujarati"},
    {"code": "ht", "name": "Haitian Creole"},
    {"code": "ha", "name": "Hausa"},
    {"code": "haw", "name": "Hawaiian"},
    {"code": "he", "name": "Hebrew"},
    {"code": "hi", "name": "Hindi"},
    {"code": "hu", "name": "Hungarian"},
    {"code": "is", "name": "Icelandic"},
    {"code": "id", "name": "Indonesian"},
    {"code": "it", "name": "Italian"},
    {"code": "ja", "name": "Japanese"},
    {"code": "jw", "name": "Javanese"},
    {"code": "kn", "name": "Kannada"},
    {"code": "kk", "name": "Kazakh"},
    {"code": "km", "name": "Khmer"},
    {"code": "ko", "name": "Korean"},
    {"code": "lo", "name": "Lao"},
    {"code": "la", "name": "Latin"},
    {"code": "lv", "name": "Latvian"},
    {"code": "ln", "name": "Lingala"},
    {"code": "lt", "name": "Lithuanian"},
    {"code": "lb", "name": "Luxembourgish"},
    {"code": "mk", "name": "Macedonian"},
    {"code": "mg", "name": "Malagasy"},
    {"code": "ms", "name": "Malay"},
    {"code": "ml", "name": "Malayalam"},
    {"code": "mt", "name": "Maltese"},
    {"code": "mi", "name": "Maori"},
    {"code": "mr", "name": "Marathi"},
    {"code": "mn", "name": "Mongolian"},
    {"code": "ne", "name": "Nepali"},
    {"code": "no", "name": "Norwegian"},
    {"code": "nn", "name": "Nynorsk"},
    {"code": "oc", "name": "Occitan"},
    {"code": "ps", "name": "Pashto"},
    {"code": "fa", "name": "Persian"},
    {"code": "pl", "name": "Polish"},
    {"code": "pt", "name": "Portuguese"},
    {"code": "pa", "name": "Punjabi"},
    {"code": "ro", "name": "Romanian"},
    {"code": "ru", "name": "Russian"},
    {"code": "sa", "name": "Sanskrit"},
    {"code": "sr", "name": "Serbian"},
    {"code": "sn", "name": "Shona"},
    {"code": "sd", "name": "Sindhi"},
    {"code": "si", "name": "Sinhala"},
    {"code": "sk", "name": "Slovak"},
    {"code": "sl", "name": "Slovenian"},
    {"code": "so", "name": "Somali"},
    {"code": "es", "name": "Spanish"},
    {"code": "su", "name": "Sundanese"},
    {"code": "sw", "name": "Swahili"},
    {"code": "sv", "name": "Swedish"},
    {"code": "tl", "name": "Tagalog"},
    {"code": "tg", "name": "Tajik"},
    {"code": "ta", "name": "Tamil"},
    {"code": "tt", "name": "Tatar"},
    {"code": "te", "name": "Telugu"},
    {"code": "th", "name": "Thai"},
    {"code": "bo", "name": "Tibetan"},
    {"code": "tr", "name": "Turkish"},
    {"code": "tk", "name": "Turkmen"},
    {"code": "uk", "name": "Ukrainian"},
    {"code": "ur", "name": "Urdu"},
    {"code": "uz", "name": "Uzbek"},
    {"code": "vi", "name": "Vietnamese"},
    {"code": "cy", "name": "Welsh"},
    {"code": "yi", "name": "Yiddish"},
    {"code": "yo", "name": "Yoruba"},
]

# ── Deepgram ─────────────────────────────────────────────────────────────────
# Mix of base ISO 639-1 and BCP-47 regional variants. Entries with
# `"model": "nova"` need the legacy Nova model (deepgram.py:47 reads this).
# Multilingual code "multi" enables Nova-3's mixed-language mode.
DEEPGRAM_LANGUAGES: list[dict[str, str]] = [
    {"code": "ar", "name": "Arabic"},
    {"code": "ar-AE", "name": "Arabic (UAE)"},
    {"code": "ar-DZ", "name": "Arabic (Algeria)"},
    {"code": "ar-EG", "name": "Arabic (Egypt)"},
    {"code": "ar-IQ", "name": "Arabic (Iraq)"},
    {"code": "ar-IR", "name": "Arabic (Iran)"},
    {"code": "ar-JO", "name": "Arabic (Jordan)"},
    {"code": "ar-KW", "name": "Arabic (Kuwait)"},
    {"code": "ar-LB", "name": "Arabic (Lebanon)"},
    {"code": "ar-MA", "name": "Arabic (Morocco)"},
    {"code": "ar-PS", "name": "Arabic (Palestine)"},
    {"code": "ar-QA", "name": "Arabic (Qatar)"},
    {"code": "ar-SA", "name": "Arabic (Saudi Arabia)"},
    {"code": "ar-SD", "name": "Arabic (Sudan)"},
    {"code": "ar-SY", "name": "Arabic (Syria)"},
    {"code": "ar-TD", "name": "Arabic (Chad)"},
    {"code": "ar-TN", "name": "Arabic (Tunisia)"},
    {"code": "be", "name": "Belarusian"},
    {"code": "bn", "name": "Bengali"},
    {"code": "bs", "name": "Bosnian"},
    {"code": "bg", "name": "Bulgarian"},
    {"code": "ca", "name": "Catalan"},
    {"code": "zh", "name": "Chinese (Mandarin Simplified)"},
    {"code": "zh-CN", "name": "Chinese (Mandarin Simplified, China)"},
    {"code": "zh-Hans", "name": "Chinese (Mandarin Simplified, Hans)"},
    {"code": "zh-Hant", "name": "Chinese (Mandarin Traditional)"},
    {"code": "zh-HK", "name": "Chinese (Cantonese, Hong Kong)"},
    {"code": "zh-TW", "name": "Chinese (Mandarin Traditional, Taiwan)"},
    {"code": "hr", "name": "Croatian"},
    {"code": "cs", "name": "Czech"},
    {"code": "da", "name": "Danish"},
    {"code": "da-DK", "name": "Danish (Denmark)"},
    {"code": "nl", "name": "Dutch"},
    {"code": "nl-BE", "name": "Dutch (Belgium)"},
    {"code": "en", "name": "English"},
    {"code": "en-AU", "name": "English (Australia)"},
    {"code": "en-CA", "name": "English (Canada)"},
    {"code": "en-GB", "name": "English (United Kingdom)"},
    {"code": "en-IE", "name": "English (Ireland)"},
    {"code": "en-IN", "name": "English (India)"},
    {"code": "en-NZ", "name": "English (New Zealand)"},
    {"code": "en-US", "name": "English (United States)"},
    {"code": "et", "name": "Estonian"},
    {"code": "fi", "name": "Finnish"},
    {"code": "fr", "name": "French"},
    {"code": "fr-CA", "name": "French (Canada)"},
    {"code": "de", "name": "German"},
    {"code": "de-CH", "name": "German (Switzerland)"},
    {"code": "el", "name": "Greek"},
    {"code": "he", "name": "Hebrew"},
    {"code": "hi", "name": "Hindi"},
    {"code": "hi-Latn", "name": "Hindi (Latin script / Hinglish)", "model": "nova"},
    {"code": "hu", "name": "Hungarian"},
    {"code": "id", "name": "Indonesian"},
    {"code": "it", "name": "Italian"},
    {"code": "ja", "name": "Japanese"},
    {"code": "kn", "name": "Kannada"},
    {"code": "ko", "name": "Korean"},
    {"code": "ko-KR", "name": "Korean (South Korea)"},
    {"code": "lv", "name": "Latvian"},
    {"code": "lt", "name": "Lithuanian"},
    {"code": "mk", "name": "Macedonian"},
    {"code": "ms", "name": "Malay"},
    {"code": "mr", "name": "Marathi"},
    {"code": "multi", "name": "Multilingual (mixed-language)"},
    {"code": "no", "name": "Norwegian"},
    {"code": "fa", "name": "Persian"},
    {"code": "pl", "name": "Polish"},
    {"code": "pt", "name": "Portuguese"},
    {"code": "pt-BR", "name": "Portuguese (Brazil)"},
    {"code": "pt-PT", "name": "Portuguese (Portugal)"},
    {"code": "ro", "name": "Romanian"},
    {"code": "ru", "name": "Russian"},
    {"code": "sr", "name": "Serbian"},
    {"code": "sk", "name": "Slovak"},
    {"code": "sl", "name": "Slovenian"},
    {"code": "es", "name": "Spanish"},
    {"code": "es-419", "name": "Spanish (Latin America)"},
    {"code": "sv", "name": "Swedish"},
    {"code": "sv-SE", "name": "Swedish (Sweden)"},
    {"code": "tl", "name": "Tagalog"},
    {"code": "ta", "name": "Tamil"},
    {"code": "te", "name": "Telugu"},
    {"code": "th", "name": "Thai"},
    {"code": "th-TH", "name": "Thai (Thailand)"},
    {"code": "tr", "name": "Turkish"},
    {"code": "uk", "name": "Ukrainian"},
    {"code": "ur", "name": "Urdu"},
    {"code": "vi", "name": "Vietnamese"},
]

# ── ElevenLabs Scribe v1 ─────────────────────────────────────────────────────
# Accepts ISO 639-1 or ISO 639-3. We prefer 639-1 where available, fall back
# to 639-3 for a few (Cantonese, Filipino, Asturian, Northern Sotho).
# Source page groups by accuracy tier; we flatten + sort alphabetically here.
ELEVENLABS_LANGUAGES: list[dict[str, str]] = [
    {"code": "af", "name": "Afrikaans"},
    {"code": "am", "name": "Amharic"},
    {"code": "ar", "name": "Arabic"},
    {"code": "hy", "name": "Armenian"},
    {"code": "as", "name": "Assamese"},
    {"code": "ast", "name": "Asturian"},
    {"code": "az", "name": "Azerbaijani"},
    {"code": "be", "name": "Belarusian"},
    {"code": "bn", "name": "Bengali"},
    {"code": "bs", "name": "Bosnian"},
    {"code": "bg", "name": "Bulgarian"},
    {"code": "my", "name": "Burmese"},
    {"code": "yue", "name": "Cantonese"},
    {"code": "ca", "name": "Catalan"},
    {"code": "hr", "name": "Croatian"},
    {"code": "cs", "name": "Czech"},
    {"code": "da", "name": "Danish"},
    {"code": "nl", "name": "Dutch"},
    {"code": "en", "name": "English"},
    {"code": "et", "name": "Estonian"},
    {"code": "fil", "name": "Filipino"},
    {"code": "fi", "name": "Finnish"},
    {"code": "fr", "name": "French"},
    {"code": "gl", "name": "Galician"},
    {"code": "lg", "name": "Ganda"},
    {"code": "ka", "name": "Georgian"},
    {"code": "de", "name": "German"},
    {"code": "el", "name": "Greek"},
    {"code": "gu", "name": "Gujarati"},
    {"code": "ha", "name": "Hausa"},
    {"code": "he", "name": "Hebrew"},
    {"code": "hi", "name": "Hindi"},
    {"code": "hu", "name": "Hungarian"},
    {"code": "is", "name": "Icelandic"},
    {"code": "ig", "name": "Igbo"},
    {"code": "id", "name": "Indonesian"},
    {"code": "ga", "name": "Irish"},
    {"code": "it", "name": "Italian"},
    {"code": "ja", "name": "Japanese"},
    {"code": "jv", "name": "Javanese"},
    {"code": "kn", "name": "Kannada"},
    {"code": "kk", "name": "Kazakh"},
    {"code": "km", "name": "Khmer"},
    {"code": "ko", "name": "Korean"},
    {"code": "ku", "name": "Kurdish"},
    {"code": "ky", "name": "Kyrgyz"},
    {"code": "lo", "name": "Lao"},
    {"code": "lv", "name": "Latvian"},
    {"code": "lt", "name": "Lithuanian"},
    {"code": "lb", "name": "Luxembourgish"},
    {"code": "mk", "name": "Macedonian"},
    {"code": "ms", "name": "Malay"},
    {"code": "ml", "name": "Malayalam"},
    {"code": "mt", "name": "Maltese"},
    {"code": "zh", "name": "Mandarin Chinese"},
    {"code": "mi", "name": "Maori"},
    {"code": "mr", "name": "Marathi"},
    {"code": "mn", "name": "Mongolian"},
    {"code": "ne", "name": "Nepali"},
    {"code": "nso", "name": "Northern Sotho"},
    {"code": "no", "name": "Norwegian"},
    {"code": "oc", "name": "Occitan"},
    {"code": "or", "name": "Odia"},
    {"code": "ps", "name": "Pashto"},
    {"code": "fa", "name": "Persian"},
    {"code": "pl", "name": "Polish"},
    {"code": "pt", "name": "Portuguese"},
    {"code": "pa", "name": "Punjabi"},
    {"code": "ro", "name": "Romanian"},
    {"code": "ru", "name": "Russian"},
    {"code": "sr", "name": "Serbian"},
    {"code": "sn", "name": "Shona"},
    {"code": "sd", "name": "Sindhi"},
    {"code": "sk", "name": "Slovak"},
    {"code": "sl", "name": "Slovenian"},
    {"code": "so", "name": "Somali"},
    {"code": "es", "name": "Spanish"},
    {"code": "sw", "name": "Swahili"},
    {"code": "sv", "name": "Swedish"},
    {"code": "tg", "name": "Tajik"},
    {"code": "ta", "name": "Tamil"},
    {"code": "te", "name": "Telugu"},
    {"code": "th", "name": "Thai"},
    {"code": "tr", "name": "Turkish"},
    {"code": "uk", "name": "Ukrainian"},
    {"code": "ur", "name": "Urdu"},
    {"code": "uz", "name": "Uzbek"},
    {"code": "vi", "name": "Vietnamese"},
    {"code": "cy", "name": "Welsh"},
    {"code": "wo", "name": "Wolof"},
    {"code": "xh", "name": "Xhosa"},
    {"code": "zu", "name": "Zulu"},
]

# ── Sarvam (saaras) ──────────────────────────────────────────────────────────
# All codes are BCP-47 with -IN suffix. Indic languages only.
SARVAM_LANGUAGES: list[dict[str, str]] = [
    {"code": "as-IN", "name": "Assamese"},
    {"code": "bn-IN", "name": "Bengali"},
    {"code": "brx-IN", "name": "Bodo"},
    {"code": "doi-IN", "name": "Dogri"},
    {"code": "en-IN", "name": "English (India)"},
    {"code": "gu-IN", "name": "Gujarati"},
    {"code": "hi-IN", "name": "Hindi"},
    {"code": "kn-IN", "name": "Kannada"},
    {"code": "ks-IN", "name": "Kashmiri"},
    {"code": "kok-IN", "name": "Konkani"},
    {"code": "mai-IN", "name": "Maithili"},
    {"code": "ml-IN", "name": "Malayalam"},
    {"code": "mni-IN", "name": "Manipuri"},
    {"code": "mr-IN", "name": "Marathi"},
    {"code": "ne-IN", "name": "Nepali"},
    {"code": "od-IN", "name": "Odia"},
    {"code": "pa-IN", "name": "Punjabi"},
    {"code": "sa-IN", "name": "Sanskrit"},
    {"code": "sat-IN", "name": "Santali"},
    {"code": "sd-IN", "name": "Sindhi"},
    {"code": "ta-IN", "name": "Tamil"},
    {"code": "te-IN", "name": "Telugu"},
    {"code": "ur-IN", "name": "Urdu"},
]

# ── Index by provider name ───────────────────────────────────────────────────
# None means "no canonical list — accept freeform input" (OpenRouter only).
PROVIDER_LANGUAGES: dict[str, list[dict[str, str]] | None] = {
    "openai": WHISPER_LANGUAGES,
    "local": WHISPER_LANGUAGES,
    "deepgram": DEEPGRAM_LANGUAGES,
    "elevenlabs": ELEVENLABS_LANGUAGES,
    "sargam": SARVAM_LANGUAGES,
    "openrouter": None,
}


def get_languages(provider_name: str) -> list[dict[str, str]] | None:
    """Return the supported-language list for a provider, or None if freeform.

    Raises KeyError if the provider name is unknown.
    """
    return PROVIDER_LANGUAGES[provider_name]
